### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by ByteOfBrie** [blaze7736/Dota-2-Manager#1]
I would recommend either using Godot engine or Unity.

Personally, I think that Godot is the best choice, as it is more focused on 2D games and feels like a better engine to me, but that's just my personal opinion. 

Unity is fine, but might be a little bit overkill in this case. I've used it a little bit in the past but haven't looked that much at its more recent versions.

**Comment by Izowa** [comment]
Godot use C++ which is nice installing it now to see what i think but it might work for this type of game well, so far i am liking the feel of Godot

**Comment by Izowa** [comment]
Okay after a bit of playing i think we should use unity simply for the fact that the interface is more flexible and so is the code in general

**Comment by qhnguyen95** [comment]
I think dota 2 manager gonna be 2D more on object oriented so unity or java is a good choice. What do u guys think

**Comment by Izowa** [comment]
I was thinking unity since there will be alot of GUI work and Java is a pain when it comes to GUI

**Comment by qhnguyen95** [comment]
That's very much true. I'm a beginner in Unity tho so probably have to spend more time learning that thing. I'm only in 3rd year in uni so I still haven't familiar with many programming language yet and my school teaches mostly java.

**Comment by opcon** [comment]
For a 2D game like this Unity may be overkill.

Godot is good, and since it's c++ there's lots of GUI frameworks we can use with it, it also [comes with it's own built in one](http://www.gamefromscratch.com/post/2015/02/20/Godot-Engine-Tutorial-Part-5-GUI-Programming-Using-Controls-Widgets-and-Containers.aspx).

**Comment by Izowa** [comment]
The only problem i see with Godot is it feels like it is not as flexible with scripts (from my quick use of it) and since the game will be based around a lot of background invisible scripts i feel unity would be able to handle this better, i also find that making the GUI in Godot was harder then making one in unity (this might be because i have done more work in unity) 
Discord server: https://discord.gg/01437nbyGDK4YEd4u

**Comment by ghost** [comment]
After looking at Godot I think it should be possible to do it with it, but would this kind of game not have more as a web application where people can compete against each other in leagues?

**Comment by Izowa** [comment]
so lets vote here is a straw poll: http://www.strawpoll.me/10445573

**Comment by shulcsm** [comment]
I'm not familiar with Footbal Manager but why don't you guys go for web and build something like CS manager?

**Comment by ghost** [comment]
Yerh had similar idea but after think a bit I came to conclusion that it requires a domain + server which means a sort of financial commitment. I know you can get relative cheap hosting but a application might be better to start with to see if people are into the idea.

**Comment by shulcsm** [comment]
Investment for development purpose is trivial. If you need a staging server or something i can provide it. Later on there are ways to monetize at least to cover hosting. I see no reasons to go native especially for traditional game engines since core of the game is running simulations and UI not fancy rendering and realtime operations.

**Comment by blaze7736** [comment]
I agree once we have an basic application if we wanted to take it to web we then can move to kick starter to raise the funds if there is any interest the hard part there would be valve to let us make money from the property hence any thing that requires funding would be hard to achive

**Comment by ghost** [comment]
You are making a good point, with web it also become easier for multi-platform support. It also becomes easier to implement the competitive aspect if that were to be the case.

**Comment by ichti-git** [comment]
I agree that a website would be nice. I would prefer playing with other people at least.

**Comment by ghost** [comment]
The question is what people are up for to develop

**Comment by Izowa** [comment]
We have decided on unity ty all for contribution
